PROJECT = simple_cache
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0


DEPS = resource_discovery  simple_cache  recon mnesia_test
dep_recon = hex 2.5.4

FORCE_REBUILD = $(DEPS)

include erlang.mk
