PROJECT = hello_bootstrap
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

# Whitespace to be used when creating files from templates.
SP = 2

DEPS = cowboy
dep_cowboy_commit:
#BUILD_DEPS += relx
include erlang.mk
