# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
# export LS_OPTIONS='--color=auto'
# eval "`dircolors`"
# alias ls='ls $LS_OPTIONS'
# alias ll='ls $LS_OPTIONS -l'
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'	
# startup run


alias ls='ls --color'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias la='ls -A'
alias ll='ls -lh'
alias lh='ls -lh'
alias rt='bitcoin-cli -regtest'

#if [ -f /root/start_up.sh ]; then
#      source /root/start_up.sh
#fi
export PATH=$PATH:/data/rabbitmq_server-3.6.9/sbin
export PATH=$PATH:/usr/local/lib/erlang


ROOTDIR=/usr/local/lib/erlang
export BINDIR=$ROOTDIR/erts-5.5.5/bin

