#FROM erlang:17.5.6.10
#FROM  erlang:17

FROM   erlang:18.3.4.11
#FROM  erlang:17

# install  software
RUN apt-get update
RUN apt-get install  -y aptitude vim zip gdb net-tools sudo ssh less tmux tcpdump telnet strace 

RUN service ssh restart


# copy file
RUN mkdir /data
ADD amqp_client /data/amqp_client
ADD client_example /data/client_example



# compile
RUN cd /data/amqp_client && make
#RUN cd /data/client_example & make
