PROJECT = webchat
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0


include ../../../../rabbitmq-components.mk
include ../../../../erlang.mk



# Make sure we know where the applications are located.
ROOT_DIR ?= ../..
APPS_DIR ?= ..
DEPS_DIR ?= ../../deps

include $(ROOT_DIR)/erlang.mk
