PROJECT = apps_dir_deps_out_project
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = myproject
#LOCAL_DEPS = myproject  # 用这个不能生效 必须用 DEPS


include rabbitmq-components.mk
include erlang.mk
