CXX = gcc
CXXFLAGS +=-g -Wall -Wextra


TARGETS = icmptime
TARGETS_C_FILE= $(TARGETS).c

CLEANUP = "rm -f $(TARGETS) *.o"

all:$(TARGETS)

clean:
	$(CLEANUP)

#root@10-160-162-26:~/program/raw/icmptime# ./icmptime  114.113.199.15
#▒ C
#wrote 114.113.199.15 20 chars, ret=20
#orig = 35425343, recv = 35426278
#adjustment = 935 ms
#correction = 0 sec, 935000 usec
