
PROGS =	 main main1

all:	${PROGS}

main:	linklist.o log.o main.o memory.o 
#${CC} ${CFLAGS} -o $@  $

main1:	linklist.o log.o main1.o memory.o 
#		${CC} ${CFLAGS} -o $@


clean:
		rm -f ${PROGS} *.o
