PROJECT = simple_cache_http
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0



DEPS =  gen_web_server  http_interface  resource_discovery  simple_cache

FORCE_REBUILD = $(DEPS)

include erlang.mk
