PROJECT = simple_cache_tcp
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = tcp_interface  resource_discovery  simple_cache recon
dep_recon = hex 2.5.4

FORCE_REBUILD = $(DEPS)

include erlang.mk
