%% ---
%%  Excerpted from "Programming Erlang, Second Edition",
%%  published by The Pragmatic Bookshelf.
%%  Copyrights apply to this code. It may not be used to create training material, 
%%  courses, books, articles, and the like. Contact us if you are in doubt.
%%  We make no guarantees that this code is fit for any purpose. 
%%  Visit http://www.pragmaticprogrammer.com/titles/jaerlang2 for more book information.
%%---
-module(my_alarm_handler).
-behaviour(gen_event).

%% gen_event callbacks
-export([init/1, code_change/3, handle_event/2, handle_call/2, 
	 handle_info/2, terminate/2]).

%% init(Args) must return {ok, State}
init(Args) ->
    io:format("*** my_alarm_handler init:~p~n",[Args]),
    {ok, 0}.

% The alarm handler is part of the SASL application.
% When writing new event handlers for the alarm handler, the following events must be handled:
% {set_alarm, {AlarmId, AlarmDescr}}
% This event is generated by alarm_handler:set_alarm({AlarmId, AlarmDecsr}).
handle_event({set_alarm, {AlarmId, tooHot}}, N) ->
    error_logger:error_msg("*** Tell the Engineer to turn on the fan~n"),
    {ok, N+1};
% {clear_alarm, AlarmId}
% This event is generated by alarm_handler:clear_alarm(AlarmId).
handle_event({clear_alarm, AlarmId}, N) ->
    error_logger:error_msg("*** Danger over. Turn off the fan~n"),
    {ok, N};
handle_event(Event, N) ->
    io:format("*** unmatched event:~p~n",[Event]),
    {ok, N}.
    
handle_call(_Request, N) -> Reply = N, {ok, Reply,  N}.
handle_info(_Info, N)    -> {ok, N}.

terminate(_Reason, _N)   -> ok.
code_change(_OldVsn, State, _Extra) -> {ok, State}.

start() ->
    % The alarm handler process is a gen_event event manager process that receives alarms in the system. 
    alarm_handler:set_alarm(tooHot),
    gen_event:swap_handler(alarm_handler, {alarm_handler, swap}, {my_alarm_handler, xyz}),
    alarm_handler:get_alarms(),
    alarm_handler:set_alarm(tooHot),
    alarm_handler:clear_alarm(tooHot),
    'this is an end'.
