PROJECT = hello_release_apps_dir
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

BUILD_DEPS += bbmustache relx
dep_bbmustache = git https://github.com/soranoba/bbmustache.git master
dep_relx = git https://github.com/erlware/relx.git  main


LOCAL_DEPS = webchat


include erlang.mk
