PROJECT = webchat
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0
#PROJECT_MOD = rabbit_prelaunch_app  # 待定




# Make sure we know where the applications are located.
ROOT_DIR ?= ../..
APPS_DIR ?= ..
DEPS_DIR ?= ../../deps

DEPS = cowboy 
DEP_PLUGINS = cowboy

include $(ROOT_DIR)/erlang.mk

