PROJECT = hello_apps_dir_deps_out
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0


DEPS = cowboy
dep_cowboy_commit = 2.7.0

DEP_PLUGINS = cowboy


# 本地依赖
LOCAL_DEPS = webchat

include erlang.mk
