echoserv: echoserv.o helper.o
	gcc -o echoserv echoserv.o helper.o -Wall -g

echoserv.o: echoserv.c helper.h
	gcc -o echoserv.o echoserv.c -c -ansi -pedantic -Wall -g

helper.o: helper.c helper.h
	gcc -o helper.o helper.c -c -ansi -pedantic -Wall -g









