root       10870  0.4  1.2 435452 101632 pts/3   Sl+  12:09   0:00 /usr/libexec/platform-python /usr/share/virt-manager/virt-install --import --connect qemu:///system --name=centos7-virt-install-cdrom --boot=hd --debug --vcpus=2 --memory=1024 --disk path=/vm/centos7-virt-install,device=disk,bus=virtio --disk /root/CentOS-7-x86_64-Minimal-2009.iso,bus=ide --network network=default --graphics vnc,listen=0.0.0.0
qemu       10904 16.5  5.1 3345356 408352 ?      Sl   12:09   0:19 /usr/libexec/qemu-kvm -name guest=centos7-virt-install-cdrom,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-12-centos7-virt-install/master-key.aes -machine pc-i440fx-rhel7.6.0,accel=kvm,usb=off,dump-guest-core=off -cpu Cooperlake,ss=on,hypervisor=on,tsc-adjust=on,umip=on,md-clear=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,hle=off,erms=off,rtm=off,avx512f=off,avx512dq=off,clwb=off,avx512cd=off,avx512bw=off,avx512vl=off,avx512vnni=off,avx512-bf16=off,taa-no=off -m 1024 -overcommit mem-lock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 9fc19385-21a5-426a-b8fc-869d8a95973f -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=38,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x4.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x4 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x4.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x4.0x2 -blockdev {"driver":"file","filename":"/vm/centos7-virt-install","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"driver":"qcow2","file":"libvirt-2-storage","backing":null} -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=libvirt-2-format,id=virtio-disk0,bootindex=1 -blockdev {"driver":"file","filename":"/root/CentOS-7-x86_64-Minimal-2009.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"driver":"raw","file":"libvirt-1-storage"} -device ide-hd,bus=ide.0,unit=0,drive=libvirt-1-format,id=ide0-0-0 -netdev tap,fd=40,id=hostnet0 -device e1000,netdev=hostnet0,id=net0,mac=52:54:00:fc:a6:06,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 0.0.0.0:0 -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
root       10933  0.3  0.6 646584 50176 pts/3    Sl+  12:09   0:00 virt-viewer --connect qemu:///system --wait centos7-virt-install-cdrom
root       11036  0.0  0.0  12136  1036 pts/1    S+   12:11   0:00 grep --color=auto qemu


-blockdev {"driver":"file","filename":"/vm/centos7-virt-install","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"} \
-blockdev {"node-name":"libvirt-2-format","read-only":false,"driver":"qcow2","file":"libvirt-2-storage","backing":null} \
-device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=libvirt-2-format,id=virtio-disk0,bootindex=1 \
-blockdev {"driver":"file","filename":"/root/CentOS-7-x86_64-Minimal-2009.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} \
-blockdev {"node-name":"libvirt-1-format","read-only":false,"driver":"raw","file":"libvirt-1-storage"} \
-device ide-hd,bus=ide.0,unit=0,drive=libvirt-1-format,id=ide0-0-0
