PROJECT = apps_dir_deps_out_project
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0


#DEPS = rabbit cowboy cowlib ranch recon
DEPS = myproject 
LOCAL_DEPS = myproject

include rabbitmq-components.mk
include erlang.mk
